### ISSUE TITLE
TypeError: this._construct is not a function

### ISSUE THREAD

**Issue by simonbcn** [bo32/gnome-shell-extension-currency-converter#7]
```
Arch Linux
GNOME Shell 3.32.0
gnome-shell-extension-currency-converter v11
```

After update Gnome Shell to version 3.32, this extension doesn't work. The log shows an error:
```
gnome-shell[836]: Extension "currencyconverter@david.bonnal.gmail.com" had error: TypeError: this._construct is not a function
```

**Comment by bo32** [comment]
Hi sorry for the late reply. Seems like that was a common issue when updating to 3.32 (I still haven't), as others were also impacted: https://github.com/micheleg/dash-to-dock/issues/877
They made some corrections, I'll try to get inspiration in order to fix it as soon as I can.

**Comment by bo32** [comment]
please give it a try now (fix available in the master branch - the new version is still not available on the Gome SHell Extensions websites, still pending for approval).

**Comment by simonbcn** [comment]
The new version is now available on the Gnome Shell extensions website and works well. 
Thanks.
